# Generated by Django 2.1.5 on 2019-02-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='todos',
            new_name='todo',
        ),
    ]
