# Generated by Django 2.1.5 on 2019-02-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190131_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todo',
            field=models.CharField(max_length=155),
        ),
    ]
