# Generated by Django 2.1.5 on 2019-02-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190131_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
    ]
